server:
  port: 8080
#  servlet:
#    context-path: /journal

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true

weather:
  api:
    key: 377916ec17580a35ae18718f6da1db00
