#spring:
#  application:
#    name: Journal-App
#
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: journaldb
#      auto-index-creation: true

spring:
  application:
    name: Journal-App
  profiles:
    active: dev

#logging:
#  level:
##    net.digest.journalAPP: DEBUG
#     net.digest.journalAPP: TRACE